### ISSUE TITLE
Implement the Setting component

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#13]
- [ ] Design of the CSS  part of the component

**Comment by RaresGherasim** [comment]
- [x] The Settings component should create the map and the player, so the generation of those elements should be moved here from Game component
- [x] The Settings component will have a query where it will ask for name, number of rows and columns 
- [x] The settings component will have as parameters a name, number of rows and number of columns, that will be use as default values for the query
- [x] The query will validate the requested values, making sure the rows and columns are at greater then 5

**Wait for the validation of sub-tasks from @Adrian-Moldovan before starting this task **

**Comment by Adrian-Moldovan** [comment]
@Clara242000 @AnaMariaDraganuta the component is functional, but please make it pretty.
