### ISSUE TITLE
On player move, avoid implementing the map state using Array.map() method

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#20]
Currently, the map tiles property is updated by calling the Array.map() method, which is ineficient.

We should avoid the iteration and directly modifying the tile by accessing the row and col indexes and de-structuring the object.

**Comment by Miana-Neagos** [comment]
Improved/ corrected tile update logic in Game component:

- Replaced _Array.map()_ with direct row/column access for efficient tile updates
- Ensured only necessary rows are copied before updating _visited_ and _yieldValue_ properties
- Added checks to prevent redundant row updates when _row_ and _newRow_ are the same
