### ISSUE TITLE
Implement fog of war

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#22]
Be creative!

**Comment by RaresGherasim** [comment]
- [x]  1.Remove the "Visited" and "Visible" attributes from tiles
- [x]  2.Make the tiles around player position visible, the rest not visible
- [x]  3.Hide the Yield and Energy values in the tiles not visible
- [x] (temporary) Add energy level value in the tile on player position

**Comment by RaresGherasim** [comment]
**1. Remove the "Visited" and "Visible" attributes from tiles**

-  Commented the "Visited" and "Visible" divs in MapTile.jsx

**Comment by RaresGherasim** [comment]
**2.Make the tiles around player position visible, the rest not visible**

- When generating the map, in generateMapTiles.jsx, set the tiles around player initial position(one step) to have the attribute "visible" as True
- When playing, in Gams.jsx , first set the variable "Visible" as false to all tiles around new player position (2 steps) , then set the attribute as True for the tiles around player position (one step) 
- Make sure not to set the attributes outside the map (validate the tiles around player position)
- It's possible to let the attributes Visible as true for the tiles already viewed the player, by commenting the FOR block the resets the attribute in the games.jsx

**Comment by RaresGherasim** [comment]
**3.Hide the Yield and Energy values in the tiles not visible**

- In MapTile.jsx, when building the components of the tile, use the attribute Visible to decide if required energy and yield value are shown in the tile ( If the tile is visible, so the attribute is true, show the divs with requiredEnergy and yieldValue

**Comment by RaresGherasim** [comment]
**Add energy level value in the tile on player position**

- On big maps, Player component is not shown anymore when the player is going down :P
- On player position tile, add a div with player energy
