### ISSUE TITLE
Fetching questions from the-trivia-api.com

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#23]
API: https://the-trivia-api.com/docs/v2/

We should consider fetching all the questions and responses upon creating the map. The implementation should not be coupled with the app (create a separate function that provides the data).

We should consider a dependency injection in case the source will change.

**Comment by RaresGherasim** [comment]
Created inside generateMapTile component because asyncronous function
