### ISSUE TITLE
Map tiles graphical refactoring

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#25]
- [x] The tile indexes should be commented. Don't delete the code, as we might use the info for debugging
- [x] As the tile yield becomes positive, the displayed yield icon  (clover or  mushroom) must be changed.  I suggest keeping the clover icon and eliminate the mushroom.
- [x] Optional: the tile yield color should reflect the score value (and in the future, the question difficulty). Use the color scheme from the player energy level.

**Comment by RaresGherasim** [comment]
Partialy finished.
