### ISSUE TITLE
Create the Question component

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#28]
The component main task is to display a quiz question and possible answers, the question category
and the player status (use flexbox)

Use radio buttons in order to let the user to choose his answer. Add a button with a  "Check answer" label  for setting the user answer.

Upon user response, display the result. If the answer was wrong, display the correct answer. Also, in this stage, display a "Return to map" button. Upon clicking this button, the question component should not be displayed anymore, the new player energy should be recalculated and the UI should display the map.

The component should only return in the game logic a Boolean value according to the user correct answer.

1. The component should be placed in the game component
2. The component should integrate the previously implemented Player component
3. For start, display the component above the map. 
4. Afterwards, we should display it in the middle of the screen (also considering the window scroll)

**Comment by RaresGherasim** [comment]
The Player component contains the Question component. Can be easily reversed
