### ISSUE TITLE
Consider refactoring the calculation of player energy level

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#29]
- [x] 1. The player energy level should be calculated only upon answering the quiz questions

- [x] 2. The Question Component should communicate if the player answer was correct

- [x] 3. The new energy level should be calculated outside the Game component (in the App component ?)

- [x] 4. The new energy gained by the player should consider the player answer and current map tile yield

**Comment by RaresGherasim** [comment]
3. The new energy level is calculated in Game component. I created a new variable, correctVar, that is +1 if the answer was correct and -1 if the answer was wrong. This varriable is multiplied with tile yieldValue, before adding it to playerEnergy
