### ISSUE TITLE
Treasure tile should be set upon creating the map

### ISSUE THREAD

**Issue by Adrian-Moldovan** [siit-webdev-47/treasure-hunt-game#6]
- [x] Add a new map property: hasTreasure (boolean false)
- [x] On creating the map, choose a random tile to contain the treasure (boolean true)
- [x] The corresponding MapTile component should display the 🏆 icon

**Comment by RaresGherasim** [comment]
Created a new folder Functions , a new file inside, called generateMapTiles.js and moved the functions that generate the tiles there
Added the hasTreasure property to tiles, with all the values set to False
Created a function to generate the treasure position, with random numbers depending on rows and columns, that set the hasTreasure property to true for that specific position
A new div was created , that shows the treasure icon in tile if the property hasTreasure is true
